### ISSUE TITLE
Update readme on system dependencies and run examples

### ISSUE THREAD

**Issue by dennislapchenko** [martinloesethjensen/balance-transfer-many-to-one#1]

**Comment by martinloesethjensen** [comment]
Dependencies can be viewed [here](https://github.com/martinloesethjensen/balance-transfer-many-to-one/blob/main/package.json) and I'll update the `README.md` with an example

**Comment by martinloesethjensen** [comment]
@dennislapchenko I have now updated the `README.md` so will close this issue 👍
